1)create a array

In [ ]:
import numpy as np
arr= np.array([1,2,3,4,5])
print(arr)
print (type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


2) check numpy version

In [ ]:
import numpy as np

print(np.__version__)


1.22.4


3) using tuple to create numpy array

In [ ]:
import numpy as np
tuple= (1,2,3,4,5)
print(tuple)

(1, 2, 3, 4, 5)


4) 0-D array

In [ ]:
import numpy as np
arr= np.array(42)
print(arr)
print(arr.ndim)

42
0


5) 1-D array

In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


6) 2-D array

In [ ]:
import numpy as np
arr= np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


7) 3-D array
   

In [ ]:
import numpy as np
arr= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


8) checking dimensions values

In [ ]:
import numpy as np
a=np.array(42)
b=np.array([1,2,3,4])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


8.a) RECHECKING DIMENTIONS

In [ ]:
import numpy as np
a=np.array(42)
b=np.array([1,2,3,4])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a.ndim)
print(b.ndim)
print(d.ndim)
print(c.ndim)

0
1
3
2


9) getting firsan element from array

In [ ]:
import numpy as aww
aww=aww.array([1,2,3,4])
print(aww[0])

1


10)adding elements from array

In [ ]:
import numpy as q
arr=q.array([1,2,3,4])
print([arr])
print(arr[0])
print(arr[1])
print(arr[0]+arr[1])

[array([1, 2, 3, 4])]
1
2
3


11) ACCESS 2-D ARRAY

11.1)  access element on first row second column

In [ ]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('second element on first row',a[0,1])

second element on first row 2


11.2)  access element on 2nd row,5th column

In [ ]:
import numpy as aw
a=aw.array([[1,2,3,4,5],[6,7,8,9,10]])
print ('element on 2nd row,5th column is:',a[1,4] )

element on 2nd row,5th column is: 10


12) accessing 3rd element in 2nd array in 1st array in 3-D ARRAY

In [ ]:
import numpy as aw
a=aw.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print ('3rd element in 2nd array in 1st array is :',a[0,1,2])

3rd element in 2nd array in 1st array is : 6


13) array silicing

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[1:5])

[2 3 4 5]


14) silicing from beginning and using step

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[1:8:2])

[2 4 6 8]


15) silicing in 2-D ARRAY

In [ ]:
import numpy as np
ar=np.array([[1,2,3,4],[5,6,7,8]])
print(ar[0:2,1:3])

[[2 3]
 [6 7]]


**16) silicing two arrays in 2-D ARRAY:** italicized text

In [ ]:
import numpy as np
ar=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(ar[0:2,1:4])

[[2 3 4]
 [7 8 9]]


Checking Data type of ARRAY in numpy

17)checking integer data type

In [ ]:
import numpy as np
x= np.array([1,2,3,4])
print(x.dtype)

int64


18) checking float type

In [ ]:
import numpy as np
x= np.array([1.1,2.23,3,4])
print(x.dtype)

float64


19) checking string type


In [ ]:
import numpy as np
x= np.array(['a','d','gdsdfd','j'])
print(x.dtype)

<U6


In [ ]:
import numpy as np
x= np.array(['a','d','gds','j'])
print(x.dtype)

<U3


In [ ]:
import numpy as np
arr= np.array([5,'banana',5.5])
print(arr.dtype)

<U32


**20) converting data type**

In [ ]:
import numpy as np
ar= np.array([1.1,2.1,3.1])
print(ar)
print(ar.dtype)
newar=ar.astype('i')
print(newar)
print(newar.dtype)

[1.1 2.1 3.1]
float64
[1 2 3]
int32


In [ ]:
import numpy as np
ar= np.array([1,2,3,7])
newar=ar.astype('f')
print(ar)
print(ar.dtype)

print(newar)
print(newar.dtype)

[1 2 3 7]
int64
[1. 2. 3. 7.]
float32


In [ ]:
import numpy as np
ar= np.array([1.1,2.1,3.1])
print(ar)
print(ar.dtype)
newar=ar.astype('i')
print(newar)
print(newar.dtype)

[1.1 2.1 3.1]
float64
[1 2 3]
int32


In [ ]:
import numpy as np
ar= np.array([1,2,3,0])
print(ar)
print(ar.dtype)
newar=ar.astype('bool')
print(newar)
print(newar.dtype)

[1 2 3 0]
int64
[ True  True  True False]
bool


21) Program for copy ,change the original array and display both arrays:

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=0

print(arr)
print(x)

[0 2 3 4 5]
[1 2 3 4 5]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])

arr[0]=0
x=arr.copy()
print(arr)
print(x)

[0 2 3 4 5]
[0 2 3 4 5]


22) program to view an array,change original and display both

In [ ]:
import numpy as np
arr= np.array([1,2,3,4,5])
arr[0]=0
x=arr.view()

print(arr)
print(x)

[0 2 3 4 5]
[0 2 3 4 5]


In [ ]:
import numpy as np
arr= np.array([1,2,3,4,5])
arr[0]=0
x=arr.view()
print(arr)
print(x)


[0 2 3 4 5]
[0 2 3 4 5]
